### PR TITLE
Messengersymbol white border fix

### PR DESCRIPTION
**Pull request by J3n50m4t**
The Messenger symbol over the Conversation avatar has a white border. It's colored in the Icon png of Facebook and due it's copyrights i didn't want to mix it up. 
So i created a box shadow as a overlay to fix the white border in a dark theme.

Left side before - right side after.

Previous - Actual

Hope it's better now

### CODE REVIEW

**Comment by auscompgeek** [comment]
A few comments:

1. This doesn't seem to change the "does not have the Facebook Messenger app" overlay. Inconsistency is bad.
2. In your screenshot, there is a noticeable border around the icon overlay.
3. I can't say I've been bothered by this ever, and I'm not sure whether it's worth the extra bloat and processing power required. (I know it's not a lot, but Messenger.com is fairly heavy already, and there seem to be mobile users out there. Speaking of which, I should probably go through and clean things up…)

   That said, I'll merge this iff there is at least one other person who _is_ bothered by this, and is happy with this change.

**Comment by J3n50m4t** [comment]
Few comments to your comments.

1. I didn't even know this exists - but I could add this if needed.

2.  Yeah your are right. Didn't notice it on my 4k - cant find a workaround for now as if I add a px more to the box it still exists - seems like a render error.  The only way I see is to fix this for now is editing the png.

3. I was bothered by that but its may u right - Using a pc fairly differs from mobile - I will just add this to my personal modifications. But I'm generally bothered by the pixelated icons and will recreate them for my self.

I just wanted to share my change, I totally understand your decision as its also no perfect solution.

**Comment by HatScripts** [comment]
Here's a solution that also fixes the noticeable border that @auscompgeek mentioned.

dark-messenger-icon-borders
```css
/* Messenger icon */
._2pop {
    border-radius: 50%;
    box-shadow: inset 0 0 0 3px #929292;
}

/* Facebook icon */
._2poo {
    border-radius: 50%;
    box-shadow: inset 0 0 0 3px #0084ff;
}

/* Messenger/Facebook icon - Draw dark grey border over white border */
._2pon:after {
    content: "";
    position: absolute;
    top: -1px;
    left: -1px;
    right: -1px;
    bottom: -1px;
    border-radius: 50%;
    border: 2px solid #282828;
}

/* Messenger/Facebook icons within the main wrapper */
._4sp8 ._2pon:after {
	border-color: #1e1e1e;
}
```

Also supports the small icons which appear next to received messages, as well as those shown in search results.

message example

search results example

As far as whether the original white border should bother you, I think some of us (myself included) might be influenced by things like Messenger's iOS app icon, where the blue speech bubble is shown encapsulated by white.

Messenger's iOS app icon

**Comment by auscompgeek** [comment]
@HatScripts Looks good! Feel free to open a PR.

What are the colours in the box-shadows though?

**Pull request closed without merging**
