### PR TITLE
Remove white border around messages

### PR DESCRIPTION
**Pull request by HatScripts**
A white border started appearing around messages for me today. This fixes that.

messenger-dark-theme-fix

### CODE REVIEW

**Comment by dtasev** [comment]
related #16, this might be a nicer fix as it doesn't cause any rendering artefacts, as far as I can see!

**Comment by mdczaplicki** [comment]
I'm waiting for this to be approved

**Comment by auscompgeek** [comment]
Pushed to userstyles.org. Cheers @HatScripts.

**Comment by HatScripts** [comment]
@auscompgeek No worries, though it appears this may not be working. It seems to just need `!important`, but for some reason it didn't require one when I was testing it by editing the userscript.

**Pull request merged**
