### PR TITLE
image info

### PR DESCRIPTION
**Pull request by J3n50m4t**
Fixed textcolor for Image informations

preview

Clicking Image in Conversation -> Info in upper left corner

### CODE REVIEW

**Comment by auscompgeek** [comment]
STR were difficult to understand…

**Review by auscompgeek — CHANGES_REQUESTED** [review]
Text that is black and grey without this style should not be styled the same grey.

**Comment by auscompgeek** [comment]
Also, it'd be great if your [commit messages are written nicely](http://chris.beams.io/posts/git-commit/).

Half tempted to fix these issues myself (keeping you as the author, of course).

**Comment by J3n50m4t** [comment]
Sorry for making bad commit, usually just using git for my self.

Gonna improve myself of course.

 Before my code it lookes like this here.

previous

I'm not sure if its the the color you want it, but I don't think a dark grey on grey background is the way it should be. 

Thanks anyway, keep it up - Won't happen again this way.

**Comment by auscompgeek** [comment]
Oh, I didn't mean to discourage you! It's just that I have high standards for this.

The text here that's white should stay white — it's black in Facebook's CSS rather than grey.

I'll go ahead and fix it up now. Thanks for bringing this to my attention.

**Pull request closed without merging**
